[build]
  command = "npm run build"
  publish = ".next"

[headers]
  [[headers.values]]
    key = "Cache-Control"
    value = "public, max-age=31536000, immutable"

  [[headers.for]]
    for = "/_next/static/*"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}
